version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  api:
    depends_on:
     - mongodb
    image: java-mongodb
    ports:
      - 8090:8090
    links:
      - mongodb
